/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hra_GUI;

/**
 *
 * @author Zuzana Žillová
 */
public class HraciPanel extends javax.swing.JFrame {

    /**
     * Creates new form HraciPanel
     */
    public HraciPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Rusko_Odstupy = new javax.swing.JLabel();
        Hranice = new javax.swing.JLabel();
        Skoly = new javax.swing.JLabel();
        Vysoke_skoly = new javax.swing.JLabel();
        Zakaz_vychadzania = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Rusko_Odstupy.setText("Rúško/Odstupy");
        jPanel1.add(Rusko_Odstupy);
        Rusko_Odstupy.setBounds(820, 20, 130, 40);

        Hranice.setText("Hranice");
        jPanel1.add(Hranice);
        Hranice.setBounds(820, 70, 110, 40);

        Skoly.setText("Školy");
        jPanel1.add(Skoly);
        Skoly.setBounds(820, 120, 120, 40);

        Vysoke_skoly.setText("Vysoke školy");
        jPanel1.add(Vysoke_skoly);
        Vysoke_skoly.setBounds(820, 170, 120, 40);

        Zakaz_vychadzania.setText("Zákaz vychádzania");
        jPanel1.add(Zakaz_vychadzania);
        Zakaz_vychadzania.setBounds(820, 230, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hranice;
    private javax.swing.JLabel Rusko_Odstupy;
    private javax.swing.JLabel Skoly;
    private javax.swing.JLabel Vysoke_skoly;
    private javax.swing.JLabel Zakaz_vychadzania;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
