/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hra_GUI;

import java.awt.Dimension;

/**
 *
 * @author Zuzana Žillová
 */
public class HraciPanel extends javax.swing.JFrame {

    /**
     * Creates new form HraciPanel
     */
    public HraciPanel() {
        setPreferredSize( new Dimension( 1400,750 ) );
        initComponents();
        setSize( 1,1 );
        setVisible(true);
        setDefaultCloseOperation( EXIT_ON_CLOSE );
        setTitle( "SKovid" );
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hlavnyPanel = new javax.swing.JPanel();
        pozadie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 750));

        hlavnyPanel.setPreferredSize(new java.awt.Dimension(1400, 750));

        pozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRA_Kresbicky/Pozadie.jpg"))); // NOI18N

        javax.swing.GroupLayout hlavnyPanelLayout = new javax.swing.GroupLayout(hlavnyPanel);
        hlavnyPanel.setLayout(hlavnyPanelLayout);
        hlavnyPanelLayout.setHorizontalGroup(
            hlavnyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hlavnyPanelLayout.createSequentialGroup()
                .addComponent(pozadie, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hlavnyPanelLayout.setVerticalGroup(
            hlavnyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hlavnyPanelLayout.createSequentialGroup()
                .addComponent(pozadie, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(hlavnyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlavnyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hlavnyPanel;
    private javax.swing.JLabel pozadie;
    // End of variables declaration//GEN-END:variables
}
